---
# This playbook install a basic user with the login keys

- name: copy ubuntu authorize_keys
  authorized_key: user=ubuntu key="{{ lookup('file', '/etc/ansible/playbooks/creds/ubuntu.pub') }}"
  tags:
   - configuration
   - security

- name: copy root authorize_keys
  authorized_key: user=root key="{{ lookup('file', '/etc/ansible/playbooks/creds/ubuntu.pub') }}"
  tags:
   - configuration
   - security

- name: copy .bash_profile for ubuntu
  tags:
   - configuration
  copy: src=home/ubuntu/.bash_profile dest=/home/ubuntu/.bash_profile owner=ubuntu group=ubuntu mode=644

- name: copy .bash_profile for root
  tags:
   - configuration
  copy: src=root/.bash_profile dest=/root/.bash_profile owner=root group=root mode=644

- name: copy .vimrc for ubuntu
  tags:
   - configuration
  copy: src=home/ubuntu/.vimrc dest=/home/ubuntu/.vimrc owner=ubuntu group=ubuntu mode=644

- name: copy .vimrc for root
  tags:
   - configuration
  copy: src=root/.vimrc dest=/root/.vimrc owner=root group=root mode=644


