---
### global settings for your infrastructure ### 

# common user to deploy across the infrastructure
# the user will be given sudo privilages under role/common/files/etc/sudoers file 
# ideally your admin user, not root ;-)
user_name: 'splunk-admin'

# password to set for the user above in encrypted format, similat to /etc/shadow
user_pass: '$6$MO3mawdB$gQkwyvLLJ3SJzvqcnUK4Tcrzqm1OWdAXqzpMGaM66VKjIkKIDDunHSfShIQHEZSYNWBd4NcSfUbzCitmMsAWw.'

# ssh key to copy over for the user above
key_file: '/home/splunk-admin/.ssh/id_rsa.pub' 

#EC2 Host Key Pair Name. Make sure you configure this under .ssh/id_rsa 
key_pair: 'ansible'
