---
####################################



####AWS INSTANCE CONFIG####

- name: Creating clusters 
  hosts: localhost
  gather_facts: False

# Define Specific Settings 
  vars:
    keypair: bsides_demo
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-9a562df2
    region: us-east-1
    vpc_subnet: subnet-f5d967ac
  tasks:
# creates 5 web servers
    - name: Launching search heads
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         region: "{{ region }}"
         vpc_subnet_id: "{{ vpc_subnet }}"
         assign_public_ip: yes
         wait: true
         exact_count: 5
         count_tag: 
           role: web_server
         instance_tags:
           role: web_server
           Name: "web_server_bsides"
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=web_server
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances


- name: apply common configuration to all nodes
  hosts: '*'
  user: ubuntu
  sudo: yes
  roles:
    - common

- name: apply web_server configuration 
  hosts: web_server 
  user: ubuntu
  sudo: yes
  roles:
    - web_server


