---
# install apache on web servers

#DEBIAN INSTALL APACHE 

- name: install apache CENTOS
  tags:
   - configuration
   - centos
  yum: name={{ item }} state=present
  with_items:
   - httpd
  when: ansible_distribution == "CentOS"

#DEBIAN INSTALL APACHE


- name: install apache DEBIAN
  tags:
   - configuration
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - apache2
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  
